#pragma once

#include <format>
#include <string>

namespace D2::Data
{
    enum class Zone : uint16_t
    {
        Invalid,
        // Act1
        Act1_Start,
        Act1_RogueEncampment = Act1_Start,
        Act1_BloodMoor,
        Act1_ColdPlains,
        Act1_StonyField,
        Act1_DarkWood,
        Act1_BlackMarsh,
        Act1_TamoeHighland,
        Act1_DenOfEvil,
        Act1_CaveLevel1,
        Act1_UndergroundPassage,
        Act1_HoleLevel1,
        Act1_PitLevel1,
        Act1_CaveLevel2,
        Act1_UndergroundPassageLevel2,
        Act1_HoleLevel2,
        Act1_PitLevel2,
        Act1_BurialGrounds,
        Act1_Crypt,
        Act1_Mausoleum,
        Act1_ForgottenTower,
        Act1_TowerCellarLevel1,
        Act1_TowerCellarLevel2,
        Act1_TowerCellarLevel3,
        Act1_TowerCellarLevel4,
        Act1_Bloodthrone,
        Act1_MonasteryGate,
        Act1_OuterCloister,
        Act1_Barracks,
        Act1_JailLevel1,
        Act1_JailLevel2,
        Act1_JailLevel3,
        Act1_InnerCloister,
        Act1_Cathedral,
        Act1_CatacombsLevel1,
        Act1_CatacombsLevel2,
        Act1_CatacombsLevel3,
        Act1_CatacombsLevel4,
        Act1_Tristram,
        Act1_End,
        // Act2
        Act2_Start,
        Act2_LutGholein = Act2_Start,
        Act2_RockyWaste,
        Act2_DryHills,
        Act2_FarOasis,
        Act2_LostCity,
        Act2_ValleyOfSnakes,
        Act2_CanyonOfTheMagi,
        Act2_SewersLevel1,
        Act2_SewersLevel2,
        Act2_SewersLevel3,
        Act2_HaremLevel1,
        Act2_HaremLevel2,
        Act2_PalaceCellarLevel1,
        Act2_PalaceCellarLevel2,
        Act2_PalaceCellarLevel3,
        Act2_StonyTombLevel1,
        Act2_HallsOfTheDeadLevel1,
        Act2_HallsOfTheDeadLevel2,
        Act2_ClawViperTempleLevel1,
        Act2_TreasureVault,
        Act2_HallsOfTheDeadLevel3,
        Act2_RitualChamber,
        Act2_MaggotLairLevel1,
        Act2_MaggotLairLevel2,
        Act2_MaggotLairLevel3,
        Act2_TalRashasTomb1 = Act2_MaggotLairLevel3 + 2,
        Act2_TalRashasTomb2,
        Act2_TalRashasTomb3,
        Act2_TalRashasTomb4,
        Act2_TalRashasTomb5,
        Act2_TalRashasTomb6,
        Act2_TalRashasTomb7,
        Act2_DurielsLair,
        Act2_ArcaneSanctuary,
        Act2_End,
        // Act3
        Act3_Start = Act2_End,
        Act3_KurastDocks = Act3_Start,
        Act3_SpiderForest,
        Act3_GreatMarsh,
        Act3_FlayerJungle,
        Act3_LowerKurast,
        Act3_KurastBazaar,
        Act3_UpperKurast,
        Act3_KurastCauseway,
        Act3_Travincal,
        Act3_ArachnidLair,
        Act3_SpiderCavern,
        Act3_SwampyPitLevel1,
        Act3_SwampyPitLevel2,
        Act3_FlayerDungeonLevel1,
        Act3_FlayerDungeonLevel2,
        Act3_FlayerDungeonLevel3,
        Act3_SewersLevel1 = Act3_FlayerDungeonLevel3 + 2,
        Act3_SewersLevel2,
        Act3_RuinedTemple,
        Act3_DisusedFane,
        Act3_ForgottenReliquary,
        Act3_ForgottenTemple,
        Act3_RuinedFane,
        Act3_DisusedReliquary,
        Act3_DuranceOfHateLevel1,
        Act3_DuranceOfHateLevel2,
        Act3_SeatOfHatred,
        Act3_End,
        // Act4
        Act4_Start = Act3_End,
        Act4_PandemoniumFortress = Act4_Start,
        Act4_OuterSteppes,
        Act4_PlainsOfDespair,
        Act4_CityOfTheDamned,
        Act4_RiverOfFlame,
        Act4_ChaosSanctuary,
        Act4_End,
        // Act5
        Act5_Start = Act4_End,
        Act5_Harrogath = Act5_Start,
        Act5_BloodyFoothills,
        Act5_FrigidHighlands,
        Act5_ArreatPlateau,
        Act5_CrystallinePassage,
        Act5_FrozenRiver,
        Act5_GlacialTrail,
        Act5_DrifterCavern,
        Act5_FrozenTundra,
        Act5_AncientsWay,
        Act5_IcyCellar,
        Act5_ArreatSummit,
        Act5_NihlathaksTemple,
        Act5_HallsOfAnguish,
        Act5_HallsOfPain,
        Act5_HallsOfTorment,
        Act5_HallsOfVaught,
        Act5_WorldstoneKeepLevel1 = 128,
        Act5_WorldstoneKeepLevel2,
        Act5_Antechamber,
        Act5_ThroneOfDestruction,
        Act5_WorldstoneChamber,
        Act5_End,
        // Median Challenges
        MXL_Start = Act5_End,
        SecretCowLevel = MXL_Start,
        TranAthulua = 217,
    };

    std::string to_string(Zone zone);
}
