name: Build and publish when tag added

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release32

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    
    - name: Cache Godot Build Tools
      uses: actions/cache@v4
      with:
        path: build/tools/godot
        key: godot-4.5.1_build_tools

    - name: Cache Godot _deps
      uses: actions/cache@v4
      with:
        path: |
          build/${{env.BUILD_TYPE}}/_deps/godot-cpp-build
          build/${{env.BUILD_TYPE}}/_deps/godot-cpp-src
          build/${{env.BUILD_TYPE}}/_deps/godot-cpp-subbuild
        key: godot-4.5_deps

    - name: Configure CMake
      run: cmake --preset ${{env.BUILD_TYPE}}

    - name: Build & Package
      run: cmake --build --preset ${{env.BUILD_TYPE}} --target package

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/D2Hub.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
